version: "3"

services:
  desa:
    image: docker.io/dgin/sistemasdesa_rhel:v2
    environment:
      - PASSWORD=mipassword
    ports:
      - "8082:80"
      - "8083:8080"
      - "8084:8084"
    volumes:
      - ./html:/var/www/html
      - ./node:/root/node
      - ./php.ini:/etc/php.ini
